services:
  - type: web
    name: ingredia-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    rootDir: backend
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: OCR_SPACE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: OPENFOODFACTS_BASE_URL
        value: https://world.openfoodfacts.org/api/v2/product
