import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";

const Disclaimer = () => {
    const navigate = useNavigate();
    return (
        <div className="px-5 pt-4 pb-8 space-y-5">
            <button onClick={() => navigate(-1)} className="h-10 w-10 rounded-full glass grid place-items-center">
                <ArrowLeft className="h-5 w-5" />
            </button>
            <h1 className="text-2xl font-bold text-foreground">Disclaimer</h1>
            <div className="glass rounded-2xl p-5 shadow-card space-y-4 text-sm text-foreground leading-relaxed">
                <p className="font-semibold">Educational Purpose Only</p>
                <p>
                    Ingredia provides educational nutritional guidance based on publicly available food science information. The health scores, ingredient classifications, and AI-generated explanations are intended for informational purposes only.
                </p>
                <p className="font-semibold">Not Medical Advice</p>
                <p>
                    This application does not constitute medical advice, diagnosis, or treatment recommendations. The information provided should not be used as a substitute for professional medical advice from a qualified healthcare provider or registered nutritionist.
                </p>
                <p className="font-semibold">Data Accuracy</p>
                <p>
                    Product information is sourced from Open Food Facts, a collaborative open-source database. While we strive for accuracy, ingredient data may be incomplete, outdated, or incorrect. Always verify critical information by reading the actual product label.
                </p>
                <p className="font-semibold">AI-Generated Content</p>
                <p>
                    AI-powered explanations are generated by Google Gemini and may occasionally produce inaccurate or incomplete information. These responses should be treated as general guidance, not authoritative health advice.
                </p>
                <p className="font-semibold">Allergen Warning</p>
                <p>
                    Ingredia does not guarantee detection of all allergens. If you have food allergies or sensitivities, always read the complete product label and consult your healthcare provider before consuming any product.
                </p>
                <p className="text-muted-foreground text-xs pt-2">
                    By using Ingredia, you acknowledge and accept these limitations.
                </p>
            </div>
        </div>
    );
};

export default Disclaimer;
